# Generated by Django 4.2.7 on 2023-11-13 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Show', '0003_model_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model_file',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image_File/'),
        ),
        migrations.AlterField(
            model_name='model_post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image_Post/'),
        ),
    ]
