# Generated by Django 4.2.7 on 2023-11-13 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Show', '0004_alter_model_file_image_alter_model_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model_file',
            name='file',
            field=models.FileField(default=None, null=True, upload_to='doc/'),
        ),
        migrations.AlterField(
            model_name='model_file',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='model_post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
