# Generated by Django 4.2.7 on 2023-11-13 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Show', '0005_alter_model_file_file_alter_model_file_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model_file',
            name='file',
            field=models.FileField(default=None, null=True, upload_to='document/'),
        ),
        migrations.AlterField(
            model_name='model_file',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image_document/'),
        ),
        migrations.AlterField(
            model_name='model_post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image_post/'),
        ),
    ]
